### ISSUE TITLE
.net core support?

### ISSUE THREAD

**Issue by softwareguy74** [onovotny/dynamodb-geo-csharp#3]
Does this work with .net core?

**Comment by onovotny** [comment]
I'm not totally sure -- I need to see if the underlying dependencies support it first.

**Comment by onovotny** [comment]
Okay, answer is yes...it works. code is checked in, just need to push out a new package.

**Comment by onovotny** [comment]
Done, 1.0.1 is on NuGet with netstandard1.3 and net45 support.
